<?php
$data = array (
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '配件分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '11',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '配件分类',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '发动机',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '发动机',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '正时及传动机构',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 2,
    'id' => '48',
    'name' => '正时及传动机构',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '正时皮带',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '49',
    'name' => '正时皮带',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '正时皮带套装',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '50',
    'name' => '正时皮带套装',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '发动机本体',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 2,
    'id' => '45',
    'name' => '发动机本体',
  ),
  176 => 
  array (
    'cat_id' => '176',
    'cat_name' => '气门摇臂',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '176',
    'name' => '气门摇臂',
  ),
  177 => 
  array (
    'cat_id' => '177',
    'cat_name' => '气门挺柱',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '177',
    'name' => '气门挺柱',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '飞轮',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '142',
    'name' => '飞轮',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '进气门摇臂',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '174',
    'name' => '进气门摇臂',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '发动机皮带',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '47',
    'name' => '发动机皮带',
  ),
  175 => 
  array (
    'cat_id' => '175',
    'cat_name' => '排气门摇臂',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '175',
    'name' => '排气门摇臂',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '发动机和变速器悬置',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '19',
    'goods_num' => 0,
    'level' => 2,
    'id' => '154',
    'name' => '发动机和变速器悬置',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => '发动机右后支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '156',
    'name' => '发动机右后支架',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => '变速器左后支架胶垫',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '172',
    'name' => '变速器左后支架胶垫',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => '变速器右支架缓冲垫',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '169',
    'name' => '变速器右支架缓冲垫',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => '变速器左后支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '166',
    'name' => '变速器左后支架',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => '发动机左支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '163',
    'name' => '发动机左支架',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => '发动机后支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '160',
    'name' => '发动机后支架',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => '发动机左前支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '157',
    'name' => '发动机左前支架',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '变速器右后支架胶垫',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '173',
    'name' => '变速器右后支架胶垫',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '变速箱右支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 3,
    'id' => '170',
    'name' => '变速箱右支架',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => '变速器左支架缓冲垫',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '167',
    'name' => '变速器左支架缓冲垫',
  ),
  164 => 
  array (
    'cat_id' => '164',
    'cat_name' => '变速器支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '164',
    'name' => '变速器支架',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => '发动机前支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '161',
    'name' => '发动机前支架',
  ),
  158 => 
  array (
    'cat_id' => '158',
    'cat_name' => '发动机左后支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '158',
    'name' => '发动机左后支架',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => '发动机支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '155',
    'name' => '发动机支架',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '变速箱左支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '171',
    'name' => '变速箱左支架',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => '变速器右后支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '168',
    'name' => '变速器右后支架',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => '变速箱支架缓冲垫',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '165',
    'name' => '变速箱支架缓冲垫',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => '发动机右支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '162',
    'name' => '发动机右支架',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '发动机右前支架',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '159',
    'name' => '发动机右前支架',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '润滑系统',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 2,
    'id' => '151',
    'name' => '润滑系统',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '机油散热器(水冷)',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '153',
    'name' => '机油散热器(水冷)',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '机油冷却器(油冷)',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '152',
    'name' => '机油冷却器(油冷)',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '制动系统',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '64',
    'name' => '制动系统',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '前轮制动器组件',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '15',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '前轮制动器组件',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '前制动蹄',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '105',
    'name' => '前制动蹄',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '前制动片',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '86',
    'name' => '前制动片',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '前制动鼓',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '80',
    'name' => '前制动鼓',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '左前制动盘',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '96',
    'name' => '左前制动盘',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '前制动片磨损感应器',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '109',
    'name' => '前制动片磨损感应器',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '左前制动蹄',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '103',
    'name' => '左前制动蹄',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '左前制动片',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '84',
    'name' => '左前制动片',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '右前制动盘',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '97',
    'name' => '右前制动盘',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '左前制动鼓',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '78',
    'name' => '左前制动鼓',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '左前制动片磨损感应器',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '110',
    'name' => '左前制动片磨损感应器',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '右前制动蹄',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '104',
    'name' => '右前制动蹄',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '右前制动片',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '85',
    'name' => '右前制动片',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '前制动盘',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '98',
    'name' => '前制动盘',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '右前制动鼓',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '79',
    'name' => '右前制动鼓',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '右前制动盘磨损感应器',
    'measure_unit' => '',
    'parent_id' => '77',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '111',
    'name' => '右前制动盘磨损感应器',
  ),
  208 => 
  array (
    'cat_id' => '208',
    'cat_name' => '制动管路',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 2,
    'id' => '208',
    'name' => '制动管路',
  ),
  209 => 
  array (
    'cat_id' => '209',
    'cat_name' => '右后制动软管',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '209',
    'name' => '右后制动软管',
  ),
  213 => 
  array (
    'cat_id' => '213',
    'cat_name' => '后制动软管',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '213',
    'name' => '后制动软管',
  ),
  210 => 
  array (
    'cat_id' => '210',
    'cat_name' => '左后制动软管',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '210',
    'name' => '左后制动软管',
  ),
  214 => 
  array (
    'cat_id' => '214',
    'cat_name' => '前制动软管',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '214',
    'name' => '前制动软管',
  ),
  211 => 
  array (
    'cat_id' => '211',
    'cat_name' => '右前制动软管',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '211',
    'name' => '右前制动软管',
  ),
  212 => 
  array (
    'cat_id' => '212',
    'cat_name' => '左前制动软管',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '212',
    'name' => '左前制动软管',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => '制动泵及组件',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 2,
    'id' => '186',
    'name' => '制动泵及组件',
  ),
  190 => 
  array (
    'cat_id' => '190',
    'cat_name' => '制动真空助力器',
    'measure_unit' => '',
    'parent_id' => '186',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '190',
    'name' => '制动真空助力器',
  ),
  187 => 
  array (
    'cat_id' => '187',
    'cat_name' => '制动真空泵',
    'measure_unit' => '',
    'parent_id' => '186',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '187',
    'name' => '制动真空泵',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '后轮制动器组件',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '15',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '后轮制动器组件',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '后制动盘',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '76',
    'name' => '后制动盘',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '后制动片',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '108',
    'name' => '后制动片',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '右后制动盘',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '73',
    'name' => '右后制动盘',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '后制动蹄',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '83',
    'name' => '后制动蹄',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '后制动鼓',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '99',
    'name' => '后制动鼓',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '后制动片磨损感应器',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '112',
    'name' => '后制动片磨损感应器',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '左后制动片',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '106',
    'name' => '左后制动片',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '左后制动鼓',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '100',
    'name' => '左后制动鼓',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '左右制动蹄',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '81',
    'name' => '左右制动蹄',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '左后制动片感应器',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '113',
    'name' => '左后制动片感应器',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '右后制动片',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '107',
    'name' => '右后制动片',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '左后制动盘',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '69',
    'name' => '左后制动盘',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '右后制动鼓',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '101',
    'name' => '右后制动鼓',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '右后制动蹄',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '82',
    'name' => '右后制动蹄',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '右后制动片磨损感应器',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '114',
    'name' => '右后制动片磨损感应器',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '转向系统',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '93',
    'name' => '转向系统',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '转向助力泵及组件',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '94',
    'name' => '转向助力泵及组件',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '转向助力泵皮带',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '95',
    'name' => '转向助力泵皮带',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '空调系统',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '90',
    'name' => '空调系统',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '冷凝器 压缩机及空调管路',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '91',
    'name' => '冷凝器 压缩机及空调管路',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '空调压缩机皮带',
    'measure_unit' => '',
    'parent_id' => '91',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '92',
    'name' => '空调压缩机皮带',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => '蒸发器及暖风组件',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '180',
    'name' => '蒸发器及暖风组件',
  ),
  181 => 
  array (
    'cat_id' => '181',
    'cat_name' => '空调滤清器(内)',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '181',
    'name' => '空调滤清器(内)',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '辅料及油液',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '辅料及油液',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '专用油液',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '13',
    'goods_num' => 0,
    'level' => 2,
    'id' => '26',
    'name' => '专用油液',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '散热器止漏剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '27',
    'name' => '散热器止漏剂',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '皮革护理剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '121',
    'name' => '皮革护理剂',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '制动液',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '102',
    'name' => '制动液',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '油漆抛光剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '118',
    'name' => '油漆抛光剂',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '空调系统清洗剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '134',
    'name' => '空调系统清洗剂',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '轮辋清洗剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '115',
    'name' => '轮辋清洗剂',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '油漆清洗剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '122',
    'name' => '油漆清洗剂',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '除虫剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '119',
    'name' => '除虫剂',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '发动机清洗剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '116',
    'name' => '发动机清洗剂',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '橡胶护理剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '120',
    'name' => '橡胶护理剂',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '柏油清洗剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '117',
    'name' => '柏油清洗剂',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '发动机舱防腐剂',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '133',
    'name' => '发动机舱防腐剂',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '雨刮清洗液',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '31',
    'name' => '雨刮清洗液',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '电器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '电器',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '发电机',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '88',
    'name' => '发电机',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '发电机皮带',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '89',
    'name' => '发电机皮带',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '喇叭',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '喇叭',
  ),
  144 => 
  array (
    'cat_id' => '144',
    'cat_name' => '低音喇叭',
    'measure_unit' => '',
    'parent_id' => '143',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '144',
    'name' => '低音喇叭',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => '高音喇叭',
    'measure_unit' => '',
    'parent_id' => '143',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 3,
    'id' => '145',
    'name' => '高音喇叭',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '喇叭',
    'measure_unit' => '',
    'parent_id' => '143',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '146',
    'name' => '喇叭',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '离合器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '135',
    'name' => '离合器',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '离合器组件',
    'measure_unit' => '',
    'parent_id' => '135',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '离合器组件',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '离合器摩擦片',
    'measure_unit' => '',
    'parent_id' => '136',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '140',
    'name' => '离合器摩擦片',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '离合器分泵',
    'measure_unit' => '',
    'parent_id' => '136',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '137',
    'name' => '离合器分泵',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '离合器压盘及摩擦片套装',
    'measure_unit' => '',
    'parent_id' => '136',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '141',
    'name' => '离合器压盘及摩擦片套装',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '分离轴承',
    'measure_unit' => '',
    'parent_id' => '136',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 3,
    'id' => '138',
    'name' => '分离轴承',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '离合器压盘',
    'measure_unit' => '',
    'parent_id' => '136',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '139',
    'name' => '离合器压盘',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '冷却系',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '冷却系',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '水泵及节温器',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '60',
    'name' => '水泵及节温器',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '水泵皮带',
    'measure_unit' => '',
    'parent_id' => '60',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '61',
    'name' => '水泵皮带',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '冷却风扇',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '53',
    'name' => '冷却风扇',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '风扇皮带',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '55',
    'name' => '风扇皮带',
  ),
  182 => 
  array (
    'cat_id' => '182',
    'cat_name' => '燃油系',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '182',
    'name' => '燃油系',
  ),
  183 => 
  array (
    'cat_id' => '183',
    'cat_name' => '燃油管路',
    'measure_unit' => '',
    'parent_id' => '182',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 2,
    'id' => '183',
    'name' => '燃油管路',
  ),
  184 => 
  array (
    'cat_id' => '184',
    'cat_name' => '燃油滤清器',
    'measure_unit' => '',
    'parent_id' => '183',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '184',
    'name' => '燃油滤清器',
  ),
  188 => 
  array (
    'cat_id' => '188',
    'cat_name' => '燃油泵',
    'measure_unit' => '',
    'parent_id' => '183',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '188',
    'name' => '燃油泵',
  ),
  185 => 
  array (
    'cat_id' => '185',
    'cat_name' => '燃油压力调节器',
    'measure_unit' => '',
    'parent_id' => '183',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '185',
    'name' => '燃油压力调节器',
  ),
  189 => 
  array (
    'cat_id' => '189',
    'cat_name' => '喷油嘴',
    'measure_unit' => '',
    'parent_id' => '183',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '189',
    'name' => '喷油嘴',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '排气系统',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '123',
    'name' => '排气系统',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '排气管及组件',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '排气管及组件',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '左后三元催化器',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '131',
    'name' => '左后三元催化器',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '左前三元催化器',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '128',
    'name' => '左前三元催化器',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '后三元催化器',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '125',
    'name' => '后三元催化器',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '右后三元催化器',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '132',
    'name' => '右后三元催化器',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '中三元催化器',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 3,
    'id' => '129',
    'name' => '中三元催化器',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '三元催化器',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '126',
    'name' => '三元催化器',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '前三元催化器',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '130',
    'name' => '前三元催化器',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '右前三元催化器',
    'measure_unit' => '',
    'parent_id' => '124',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 3,
    'id' => '127',
    'name' => '右前三元催化器',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '进气系统',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '34',
    'name' => '进气系统',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => '中冷器',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 2,
    'id' => '147',
    'name' => '中冷器',
  ),
  150 => 
  array (
    'cat_id' => '150',
    'cat_name' => '右中冷器',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '150',
    'name' => '右中冷器',
  ),
  148 => 
  array (
    'cat_id' => '148',
    'cat_name' => '中冷器',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '148',
    'name' => '中冷器',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '左中冷器',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '149',
    'name' => '左中冷器',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '空气过滤系统',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 2,
    'id' => '37',
    'name' => '空气过滤系统',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '右空气滤清器芯',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '41',
    'name' => '右空气滤清器芯',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '空气滤清器芯',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '39',
    'name' => '空气滤清器芯',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '左空气滤清器芯',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '40',
    'name' => '左空气滤清器芯',
  ),
  215 => 
  array (
    'cat_id' => '215',
    'cat_name' => '用以测试的顶级分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '215',
    'name' => '用以测试的顶级分类',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '车型',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '车型',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '保时捷',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '保时捷',
  ),
  257 => 
  array (
    'cat_id' => '257',
    'cat_name' => '保时捷博斯特',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '257',
    'name' => '保时捷博斯特',
  ),
  258 => 
  array (
    'cat_id' => '258',
    'cat_name' => 'null_type',
    'measure_unit' => '',
    'parent_id' => '257',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 3,
    'id' => '258',
    'name' => 'null_type',
  ),
  262 => 
  array (
    'cat_id' => '262',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '258',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 4,
    'id' => '262',
    'name' => '2013款',
  ),
  265 => 
  array (
    'cat_id' => '265',
    'cat_name' => '2.9L',
    'measure_unit' => '',
    'parent_id' => '262',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '265',
    'name' => '2.9L',
  ),
  266 => 
  array (
    'cat_id' => '266',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '265',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '266',
    'name' => 'AT',
  ),
  263 => 
  array (
    'cat_id' => '263',
    'cat_name' => '3.4L',
    'measure_unit' => '',
    'parent_id' => '262',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '263',
    'name' => '3.4L',
  ),
  264 => 
  array (
    'cat_id' => '264',
    'cat_name' => 'AT MA123V',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '264',
    'name' => 'AT MA123V',
  ),
  259 => 
  array (
    'cat_id' => '259',
    'cat_name' => '2014款',
    'measure_unit' => '',
    'parent_id' => '258',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '259',
    'name' => '2014款',
  ),
  260 => 
  array (
    'cat_id' => '260',
    'cat_name' => '2.7L',
    'measure_unit' => '',
    'parent_id' => '259',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '260',
    'name' => '2.7L',
  ),
  261 => 
  array (
    'cat_id' => '261',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '260',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '261',
    'name' => 'AT',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '比亚迪',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '6',
    'name' => '比亚迪',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '比亚迪福莱尔',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '16',
    'name' => '比亚迪福莱尔',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => 'null_type',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 3,
    'id' => '23',
    'name' => 'null_type',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '2007款',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '18',
    'name' => '2007款',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '1.1L',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '24',
    'name' => '1.1L',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => 'MT BYD465Q',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '25',
    'name' => 'MT BYD465Q',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '2008款',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '17',
    'name' => '2008款',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '0.8L',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 5,
    'id' => '19',
    'name' => '0.8L',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => 'MT',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '21',
    'name' => 'MT',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '20',
    'name' => 'AT',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '比亚迪E6',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '7',
    'name' => '比亚迪E6',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => 'null_type',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 3,
    'id' => '12',
    'name' => 'null_type',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '2012款',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 4,
    'id' => '15',
    'name' => '2012款',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '2014款',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 4,
    'id' => '13',
    'name' => '2014款',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 4,
    'id' => '14',
    'name' => '2013款',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '进口宝马',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '3',
    'name' => '进口宝马',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '进口宝马3系',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 2,
    'id' => '8',
    'name' => '进口宝马3系',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => 'F30 335i',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 3,
    'id' => '28',
    'name' => 'F30 335i',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '42',
    'name' => '2013款',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '43',
    'name' => '3.0L',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => 'AT N55B30',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '46',
    'name' => 'AT N55B30',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '2014款',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '30',
    'name' => '2014款',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '32',
    'name' => '3.0L',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '33',
    'name' => 'AT',
  ),
  203 => 
  array (
    'cat_id' => '203',
    'cat_name' => 'E92 325i',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '203',
    'name' => 'E92 325i',
  ),
  204 => 
  array (
    'cat_id' => '204',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '204',
    'name' => '2013款',
  ),
  205 => 
  array (
    'cat_id' => '205',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '204',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '205',
    'name' => '3.0L',
  ),
  206 => 
  array (
    'cat_id' => '206',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '205',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '206',
    'name' => 'AT',
  ),
  216 => 
  array (
    'cat_id' => '216',
    'cat_name' => 'E93 330i',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '216',
    'name' => 'E93 330i',
  ),
  217 => 
  array (
    'cat_id' => '217',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '216',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '217',
    'name' => '2013款',
  ),
  218 => 
  array (
    'cat_id' => '218',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '217',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '218',
    'name' => '3.0L',
  ),
  219 => 
  array (
    'cat_id' => '219',
    'cat_name' => 'MT',
    'measure_unit' => '',
    'parent_id' => '218',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '219',
    'name' => 'MT',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => 'F34 GT 320i',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '29',
    'name' => 'F34 GT 320i',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '2014款',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '35',
    'name' => '2014款',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '2.0L',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '36',
    'name' => '2.0L',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '38',
    'name' => 'AT',
  ),
  191 => 
  array (
    'cat_id' => '191',
    'cat_name' => 'E91 320i',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '191',
    'name' => 'E91 320i',
  ),
  192 => 
  array (
    'cat_id' => '192',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '191',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '192',
    'name' => '2013款',
  ),
  193 => 
  array (
    'cat_id' => '193',
    'cat_name' => '2.0L',
    'measure_unit' => '',
    'parent_id' => '192',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 5,
    'id' => '193',
    'name' => '2.0L',
  ),
  194 => 
  array (
    'cat_id' => '194',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '193',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '194',
    'name' => 'AT',
  ),
  207 => 
  array (
    'cat_id' => '207',
    'cat_name' => 'MT',
    'measure_unit' => '',
    'parent_id' => '193',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '207',
    'name' => 'MT',
  ),
  220 => 
  array (
    'cat_id' => '220',
    'cat_name' => 'E92 335i',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '220',
    'name' => 'E92 335i',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '221',
    'name' => '2013款',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '222',
    'name' => '3.0L',
  ),
  223 => 
  array (
    'cat_id' => '223',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '222',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '223',
    'name' => 'AT',
  ),
  195 => 
  array (
    'cat_id' => '195',
    'cat_name' => 'E93 325d',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '195',
    'name' => 'E93 325d',
  ),
  196 => 
  array (
    'cat_id' => '196',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '195',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '196',
    'name' => '2013款',
  ),
  197 => 
  array (
    'cat_id' => '197',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '196',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '197',
    'name' => '3.0L',
  ),
  198 => 
  array (
    'cat_id' => '198',
    'cat_name' => 'MT',
    'measure_unit' => '',
    'parent_id' => '197',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '198',
    'name' => 'MT',
  ),
  224 => 
  array (
    'cat_id' => '224',
    'cat_name' => 'E90 318i',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '224',
    'name' => 'E90 318i',
  ),
  225 => 
  array (
    'cat_id' => '225',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '225',
    'name' => '2013款',
  ),
  226 => 
  array (
    'cat_id' => '226',
    'cat_name' => '1.8L',
    'measure_unit' => '',
    'parent_id' => '225',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '226',
    'name' => '1.8L',
  ),
  227 => 
  array (
    'cat_id' => '227',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '226',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '227',
    'name' => 'AT',
  ),
  199 => 
  array (
    'cat_id' => '199',
    'cat_name' => 'E92 330i',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '199',
    'name' => 'E92 330i',
  ),
  200 => 
  array (
    'cat_id' => '200',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '199',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '200',
    'name' => '2013款',
  ),
  201 => 
  array (
    'cat_id' => '201',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '201',
    'name' => '3.0L',
  ),
  202 => 
  array (
    'cat_id' => '202',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '202',
    'name' => 'AT',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '进口宝马5系',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 2,
    'id' => '9',
    'name' => '进口宝马5系',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => 'F10 535i',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '51',
    'name' => 'F10 535i',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '2014款',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '54',
    'name' => '2014款',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '56',
    'name' => '3.0L',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '57',
    'name' => 'AT',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => 'F07 GT 535i',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '58',
    'name' => 'F07 GT 535i',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '2014款',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '59',
    'name' => '2014款',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '62',
    'name' => '3.0L',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '62',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '63',
    'name' => 'AT',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => 'E61 523i',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '71',
    'name' => 'E61 523i',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '71',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '72',
    'name' => '2013款',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '2.5L',
    'measure_unit' => '',
    'parent_id' => '72',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '74',
    'name' => '2.5L',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '74',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '75',
    'name' => 'AT',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'F07 GT 550i',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '65',
    'name' => 'F07 GT 550i',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '67',
    'name' => '2013款',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '4.4L',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '68',
    'name' => '4.4L',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '70',
    'name' => 'AT',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '进口宝马M6',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 2,
    'id' => '11',
    'name' => '进口宝马M6',
  ),
  237 => 
  array (
    'cat_id' => '237',
    'cat_name' => 'E63 M6',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 3,
    'id' => '237',
    'name' => 'E63 M6',
  ),
  241 => 
  array (
    'cat_id' => '241',
    'cat_name' => '2010款',
    'measure_unit' => '',
    'parent_id' => '237',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '241',
    'name' => '2010款',
  ),
  242 => 
  array (
    'cat_id' => '242',
    'cat_name' => '5.0L',
    'measure_unit' => '',
    'parent_id' => '241',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '242',
    'name' => '5.0L',
  ),
  243 => 
  array (
    'cat_id' => '243',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '242',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '243',
    'name' => 'AT',
  ),
  238 => 
  array (
    'cat_id' => '238',
    'cat_name' => '2012款',
    'measure_unit' => '',
    'parent_id' => '237',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '238',
    'name' => '2012款',
  ),
  239 => 
  array (
    'cat_id' => '239',
    'cat_name' => '5.0L',
    'measure_unit' => '',
    'parent_id' => '238',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '239',
    'name' => '5.0L',
  ),
  240 => 
  array (
    'cat_id' => '240',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '239',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '240',
    'name' => 'AT',
  ),
  228 => 
  array (
    'cat_id' => '228',
    'cat_name' => 'F13 M6',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 3,
    'id' => '228',
    'name' => 'F13 M6',
  ),
  232 => 
  array (
    'cat_id' => '232',
    'cat_name' => '2013款',
    'measure_unit' => '',
    'parent_id' => '228',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 4,
    'id' => '232',
    'name' => '2013款',
  ),
  235 => 
  array (
    'cat_id' => '235',
    'cat_name' => '5.0L',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '235',
    'name' => '5.0L',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '235',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '236',
    'name' => 'AT',
  ),
  233 => 
  array (
    'cat_id' => '233',
    'cat_name' => '4.4L',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '233',
    'name' => '4.4L',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '233',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '234',
    'name' => 'AT',
  ),
  229 => 
  array (
    'cat_id' => '229',
    'cat_name' => '2014款',
    'measure_unit' => '',
    'parent_id' => '228',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '229',
    'name' => '2014款',
  ),
  230 => 
  array (
    'cat_id' => '230',
    'cat_name' => '4.4L',
    'measure_unit' => '',
    'parent_id' => '229',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '230',
    'name' => '4.4L',
  ),
  231 => 
  array (
    'cat_id' => '231',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '230',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '231',
    'name' => 'AT',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '华晨宝马',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '华晨宝马',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => '华晨宝马5系',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 2,
    'id' => '244',
    'name' => '华晨宝马5系',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => 'F18 530Li',
    'measure_unit' => '',
    'parent_id' => '244',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '245',
    'name' => 'F18 530Li',
  ),
  246 => 
  array (
    'cat_id' => '246',
    'cat_name' => '2014款',
    'measure_unit' => '',
    'parent_id' => '245',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '246',
    'name' => '2014款',
  ),
  247 => 
  array (
    'cat_id' => '247',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '246',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '247',
    'name' => '3.0L',
  ),
  248 => 
  array (
    'cat_id' => '248',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '247',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '248',
    'name' => 'AT',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => 'F18 535Li',
    'measure_unit' => '',
    'parent_id' => '244',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '249',
    'name' => 'F18 535Li',
  ),
  250 => 
  array (
    'cat_id' => '250',
    'cat_name' => '2014款',
    'measure_unit' => '',
    'parent_id' => '249',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '250',
    'name' => '2014款',
  ),
  251 => 
  array (
    'cat_id' => '251',
    'cat_name' => '3.0L',
    'measure_unit' => '',
    'parent_id' => '250',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '251',
    'name' => '3.0L',
  ),
  252 => 
  array (
    'cat_id' => '252',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '251',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '252',
    'name' => 'AT',
  ),
  253 => 
  array (
    'cat_id' => '253',
    'cat_name' => 'F18 520Li',
    'measure_unit' => '',
    'parent_id' => '244',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 3,
    'id' => '253',
    'name' => 'F18 520Li',
  ),
  254 => 
  array (
    'cat_id' => '254',
    'cat_name' => '2014款',
    'measure_unit' => '',
    'parent_id' => '253',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 4,
    'id' => '254',
    'name' => '2014款',
  ),
  255 => 
  array (
    'cat_id' => '255',
    'cat_name' => '2.0L',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 5,
    'id' => '255',
    'name' => '2.0L',
  ),
  256 => 
  array (
    'cat_id' => '256',
    'cat_name' => 'AT',
    'measure_unit' => '',
    'parent_id' => '255',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 6,
    'id' => '256',
    'name' => 'AT',
  ),
);
?>